blank_issues_enabled: false
contact_links:
    - name: Read the Docs
      url: http://handyorg.github.io
      about: Be sure you've read the docs! See English documentation here http://ghost1372.github.io